import AntdConfigProvider from "@/providers/antd-config-provider";
import AntdStylesProvider from "@/providers/antd-styles-provider";
import AuthRefreshProvider from "@/providers/auth-refresh-provider";
import NotificationPermissionProvider from "@/providers/notification-permission-provider";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Agrisa Insurance Partner Portal",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <NotificationPermissionProvider>
                    <AntdStylesProvider>
                        <AntdConfigProvider>
                            <AuthRefreshProvider>{children}</AuthRefreshProvider>
                        </AntdConfigProvider>
                    </AntdStylesProvider>
                </NotificationPermissionProvider>
            </body>
        </html>
    );
}
