import AntdConfigProvider from "@/providers/antd-config-provider";
import { Inter } from "next/font/google";
import "./globals.css";
import AntdStylesProvider from "@/providers/antd-styles-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Agrisa Insurance Partner Portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdStylesProvider>
          <AntdConfigProvider>
            {/* <CustomSidebar /> */}
            {children}
          </AntdConfigProvider>
        </AntdStylesProvider>
      </body>
    </html>
  );
}
