import { Inter } from "next/font/google";
import "./globals.css";
import CustomSidebar from "@/components/custom-sidebar";
import AntdConfigProvider from "@/providers/andtd-config-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My Admin Web",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdConfigProvider>
          <CustomSidebar />
          {children}
        </AntdConfigProvider>
      </body>
    </html>
  );
}
